config:
  viewlondonuk:DOMAIN_NAME: viewlondon.uk
  viewlondonuk:ADMIN_EMAIL:
    secure: AAABACMZLZxOYLoPYysLNoWTO2rq0iOdJRSsKEMRU+2+YfQbZR+Jt22zqCJclQ6b662kbF4OY+8=
  viewlondonuk:SITE_IMAGE_NAME: viewlondonuk/site
  viewlondonuk:SITE_BUILD_CONTEXT: ../../site
  viewlondonuk:SITE_IMAGE_TAG: latest
  viewlondonuk:APP_PORT: "3010"
  viewlondonuk:ENABLE_TLS: "true"
  viewlondonuk:PROTOCOL: https
  viewlondonuk:SITE_WORKDIR_PATH: /site
  viewlondonuk:SITE_BUILD_PHASE_TARGET: production
  viewlondonuk:CORE_STACK_NAME: Rashad/portfolio-infra/prod
  viewlondonuk:CONTACT_EMAIL: contact@viewlondon.uk
